[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
serde = "1.0.144"
env = "0.0.0"

[dependencies.mongodb]
version = "2.3.0"
features = ["tokio-sync"]
