[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
serde = "1.0.144"
env = "0.0.0"
bson = { version = "2", features = ["chrono-0_4"] }
mongodb = { version = "2.3.0", features = ["tokio-sync"] }
